// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// weighted_jaccard_sparse_fill_cpp
NumericVector weighted_jaccard_sparse_fill_cpp(const S4& x, const S4& pattern, bool transpose);
RcppExport SEXP _coconat_weighted_jaccard_sparse_fill_cpp(SEXP xSEXP, SEXP patternSEXP, SEXP transposeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const S4& >::type pattern(patternSEXP);
    Rcpp::traits::input_parameter< bool >::type transpose(transposeSEXP);
    rcpp_result_gen = Rcpp::wrap(weighted_jaccard_sparse_fill_cpp(x, pattern, transpose));
    return rcpp_result_gen;
END_RCPP
}
// weighted_jaccard_dense_cpp
NumericMatrix weighted_jaccard_dense_cpp(const S4& x, bool transpose);
RcppExport SEXP _coconat_weighted_jaccard_dense_cpp(SEXP xSEXP, SEXP transposeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type transpose(transposeSEXP);
    rcpp_result_gen = Rcpp::wrap(weighted_jaccard_dense_cpp(x, transpose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_coconat_weighted_jaccard_sparse_fill_cpp", (DL_FUNC) &_coconat_weighted_jaccard_sparse_fill_cpp, 3},
    {"_coconat_weighted_jaccard_dense_cpp", (DL_FUNC) &_coconat_weighted_jaccard_dense_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_coconat(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
