# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

weighted_jaccard_sparse_fill_cpp <- function(x, pattern, transpose = FALSE) {
    .Call(`_coconat_weighted_jaccard_sparse_fill_cpp`, x, pattern, transpose)
}

weighted_jaccard_dense_cpp <- function(x, transpose = FALSE) {
    .Call(`_coconat_weighted_jaccard_dense_cpp`, x, transpose)
}

